CREATE OR REPLACE FUNCTION public.fc_player_next_cell(p_cell uuid,p_direction text) RETURNS uuid LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_world_cells; r public.fc_world_rooms; f uuid;
BEGIN SELECT * INTO c FROM public.fc_world_cells WHERE id=p_cell; SELECT * INTO r FROM public.fc_world_rooms WHERE id=c.room_id; SELECT family_id INTO f FROM public.fc_characters WHERE owner_id=public.fc_require_uid();
 IF c.x=0 AND c.y=-1 AND p_direction='north' AND (r.template_id='10000000-0000-0000-0000-000000000005' OR r.name LIKE '%府前街%') THEN RETURN (SELECT cell.id FROM public.fc_world_cells cell JOIN public.fc_world_rooms home ON home.id=cell.room_id WHERE home.family_id=f AND home.template_id='10000000-0000-0000-0000-000000000001' AND cell.x=0 AND cell.y=1); END IF;
 IF c.x=0 AND c.y=1 AND p_direction='south' AND r.family_id=f AND r.template_id='10000000-0000-0000-0000-000000000001' THEN RETURN (SELECT cell.id FROM public.fc_world_cells cell JOIN public.fc_world_rooms street ON street.id=cell.room_id WHERE street.city_id=r.city_id AND street.family_id IS NULL AND (street.template_id='10000000-0000-0000-0000-000000000005' OR street.name LIKE '%府前街%') AND cell.x=0 AND cell.y=-1); END IF;
 RETURN public.fc_world_next_cell(p_cell,p_direction);
END $$;
CREATE OR REPLACE FUNCTION public.fc_move_world(p_direction text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE uid text:=public.fc_require_uid(); me public.fc_characters; pos public.fc_character_positions; cell public.fc_world_cells; next_cell public.fc_world_cells;
BEGIN SELECT * INTO me FROM public.fc_characters WHERE owner_id=uid; IF me.id IS NULL THEN RAISE EXCEPTION '请先入世'; END IF; PERFORM public.fc_get_world_state(); SELECT * INTO pos FROM public.fc_character_positions WHERE character_id=me.id FOR UPDATE; SELECT * INTO cell FROM public.fc_world_cells WHERE id=pos.cell_id; SELECT * INTO next_cell FROM public.fc_world_cells WHERE id=public.fc_player_next_cell(cell.id,p_direction); IF next_cell.id IS NULL THEN RAISE EXCEPTION '这里没有可通行的道路'; END IF; IF EXISTS(SELECT 1 FROM public.fc_combat_encounters WHERE character_id=me.id AND status='active') THEN RAISE EXCEPTION '战斗中不能移动'; END IF; UPDATE public.fc_character_positions SET cell_id=next_cell.id,updated_at=now() WHERE character_id=me.id; RETURN public.fc_get_world_state(); END $$;
REVOKE ALL ON FUNCTION public.fc_player_next_cell(uuid,text) FROM PUBLIC; REVOKE ALL ON FUNCTION public.fc_move_world(text) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.fc_move_world(text) TO authenticated;
