ALTER TABLE public.fc_world_rooms ADD COLUMN region_depth text NOT NULL DEFAULT 'city';
UPDATE public.fc_world_rooms SET region_depth=CASE WHEN kind='forest' AND name LIKE '%外围%' THEN 'outer' WHEN kind='forest' THEN 'inner' WHEN kind='wilderness' THEN 'outer' ELSE 'city' END;
CREATE TABLE public.fc_monster_definitions(id text PRIMARY KEY,name text NOT NULL,realm_index smallint NOT NULL,region_depth text NOT NULL,base_health numeric NOT NULL,base_attack numeric NOT NULL,base_defense numeric NOT NULL,speed numeric NOT NULL,weakness text NOT NULL,combat_note text NOT NULL,image_path text);
CREATE TABLE public.fc_combat_encounters(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),character_id uuid NOT NULL REFERENCES public.fc_characters(id),room_id uuid NOT NULL REFERENCES public.fc_world_rooms(id),monster_id text NOT NULL REFERENCES public.fc_monster_definitions(id),monster_count smallint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),status text NOT NULL DEFAULT 'active',player_health numeric NOT NULL,monster_health numeric NOT NULL,turn integer NOT NULL DEFAULT 0,result text);
ALTER TABLE public.fc_monster_definitions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.fc_combat_encounters ENABLE ROW LEVEL SECURITY; REVOKE ALL ON public.fc_monster_definitions,public.fc_combat_encounters FROM anon,authenticated;
INSERT INTO public.fc_monster_definitions VALUES('qi_stone_rat','\u523a\u6bdb\u77f3\u9f20',0,'outer',80,18,8,16,'\u706b\u3001\u96f7','\u901f\u5ea6\u5feb\u3001\u77f3\u523a\u5f39\u5c04',NULL);
INSERT INTO public.fc_monster_definitions VALUES('qi_venom_snake','\u9752\u7eb9\u6bd2\u86c7',0,'outer',90,22,7,14,'\u9633\u706b\u3001\u7206\u88c2','\u9690\u533f\u3001\u6bd2\u96fe\u3001\u6301\u7eed\u8150\u8680',NULL);
INSERT INTO public.fc_monster_definitions VALUES('qi_talisman_crow','\u7b26\u7eb8\u4e4c\u9e26',0,'outer',75,20,5,18,'\u5f3a\u5149\u3001\u6e05\u51c0','\u7b26\u706b\u4e0e\u795e\u8bc6\u5e72\u6270',NULL);
INSERT INTO public.fc_monster_definitions VALUES('foundation_turtle','\u7384\u7532\u5de8\u9f9f',1,'inner',550,95,120,5,'\u56db\u80a2\u4e0e\u5934\u90e8','\u9ad8\u9632\u5fa1\u3001\u571f\u9707\u8361\u3001\u6c34\u5e55\u53cd\u51fb',NULL);
INSERT INTO public.fc_monster_definitions VALUES('foundation_lion','\u96f7\u7eb9\u72c2\u72ee',1,'inner',480,140,55,24,'\u6c34\u571f\u9632\u5fa1','\u96f7\u66b4\u5486\u54ee\u3001\u95ea\u7535\u6251\u51fb',NULL);
INSERT INTO public.fc_monster_definitions VALUES('foundation_butterfly','\u5e7b\u5f69\u6bd2\u8776',1,'inner',360,110,35,28,'\u9501\u5b9a\u771f\u8eab','\u5e7b\u8c61\u3001\u6bd2\u7c89\u3001\u955c\u50cf',NULL);
INSERT INTO public.fc_monster_definitions VALUES('core_fire_qilin','\u91d1\u775b\u706b\u9e9f\u517d',2,'core',2800,620,420,35,'\u7384\u6c34\u3001\u51b0\u5c01','\u7834\u9690\u3001\u706b\u7130\u5410\u606f\u3001\u9e9f\u7532\u7206\u88c2',NULL);
INSERT INTO public.fc_monster_definitions VALUES('core_ice_luan','\u971c\u7ffc\u51b0\u9e3e',2,'core',2400,700,300,48,'\u706b\u3001\u96f7','\u9ad8\u7a7a\u4fef\u51b2\u3001\u51b0\u5c01\u9886\u57df',NULL);
INSERT INTO public.fc_monster_definitions VALUES('core_blood_serpent','\u5e7d\u51a5\u8840\u87d2',2,'core',3200,760,360,22,'\u81f3\u9633\u3001\u51c0\u4e16','\u8840\u96fe\u3001\u9b3c\u706b\u3001\u541e\u566c\u7075\u529b',NULL);
CREATE FUNCTION public.fc_get_combat() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; e public.fc_combat_encounters; m public.fc_monster_definitions;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid(); SELECT * INTO e FROM public.fc_combat_encounters WHERE character_id=c.id AND status='active' LIMIT 1; IF e.id IS NULL THEN RETURN jsonb_build_object('active',false); END IF; SELECT * INTO m FROM public.fc_monster_definitions WHERE id=e.monster_id; RETURN jsonb_build_object('active',true,'encounter',to_jsonb(e),'monster',to_jsonb(m),'player_realm',c.realm,'player_name',c.display_name,'player_avatar_key',c.avatar_key); END $$;
CREATE FUNCTION public.fc_use_lure() RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; p public.fc_character_positions; cell public.fc_world_cells; r public.fc_world_rooms; item public.fc_inventory_slots;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid() FOR UPDATE; SELECT * INTO p FROM public.fc_character_positions WHERE character_id=c.id; SELECT * INTO cell FROM public.fc_world_cells WHERE id=p.cell_id; SELECT * INTO r FROM public.fc_world_rooms WHERE id=cell.room_id; IF r.kind NOT IN ('wilderness','forest','road') THEN RAISE EXCEPTION '只能在野外或官道使用引妖散'; END IF; SELECT * INTO item FROM public.fc_inventory_slots WHERE character_id=c.id AND item_key='lure_powder' ORDER BY slot LIMIT 1 FOR UPDATE; IF item.slot IS NULL THEN RAISE EXCEPTION '没有引妖散'; END IF; IF item.quantity=1 THEN DELETE FROM public.fc_inventory_slots WHERE character_id=c.id AND slot=item.slot; ELSE UPDATE public.fc_inventory_slots SET quantity=quantity-1 WHERE character_id=c.id AND slot=item.slot; END IF; UPDATE public.fc_world_rooms SET encounter_rate=1 WHERE id=r.id; RETURN jsonb_build_object('message','引妖散生效：当前区域遇怪概率提升至100%，下一次判定必定遇怪。'); END $$;
CREATE FUNCTION public.fc_spawn_combat() RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; p public.fc_character_positions; cell public.fc_world_cells; r public.fc_world_rooms; m public.fc_monster_definitions; e public.fc_combat_encounters; chance numeric; allowed integer;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid() FOR UPDATE; SELECT * INTO p FROM public.fc_character_positions WHERE character_id=c.id; SELECT * INTO cell FROM public.fc_world_cells WHERE id=p.cell_id; SELECT * INTO r FROM public.fc_world_rooms WHERE id=cell.room_id; IF r.kind NOT IN ('wilderness','forest','road') THEN RETURN public.fc_get_combat(); END IF; SELECT * INTO e FROM public.fc_combat_encounters WHERE character_id=c.id AND status='active' LIMIT 1; IF e.id IS NOT NULL THEN RETURN public.fc_get_combat(); END IF; IF random()>r.encounter_rate THEN RETURN jsonb_build_object('active',false); END IF; allowed:=CASE WHEN r.region_depth='outer' THEN least(1,c.realm_index+1) WHEN r.region_depth='inner' THEN least(2,c.realm_index+1) ELSE 2 END; SELECT * INTO m FROM public.fc_monster_definitions WHERE region_depth=r.region_depth AND realm_index<=allowed ORDER BY random() LIMIT 1; IF m.id IS NULL THEN RETURN jsonb_build_object('active',false); END IF; INSERT INTO public.fc_combat_encounters(character_id,room_id,monster_id,monster_count,player_health,monster_health) VALUES(c.id,r.id,m.id,1+floor(random()*3)::int,(public.fc_get_attributes()->>'health')::numeric,m.base_health) RETURNING * INTO e; RETURN public.fc_get_combat(); END $$;
CREATE FUNCTION public.fc_resolve_combat(p_action text DEFAULT 'auto') RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; e public.fc_combat_encounters; m public.fc_monster_definitions; a numeric; damage numeric; md numeric; win boolean;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid() FOR UPDATE; SELECT * INTO e FROM public.fc_combat_encounters WHERE character_id=c.id AND status='active' LIMIT 1; IF e.id IS NULL THEN RETURN public.fc_get_combat(); END IF; SELECT * INTO m FROM public.fc_monster_definitions WHERE id=e.monster_id; a:=(public.fc_get_attributes()->>'attack')::numeric; damage:=greatest(1,a-m.base_defense*.35); md:=greatest(1,m.base_attack-(public.fc_get_attributes()->>'defense')::numeric*.25); UPDATE public.fc_combat_encounters SET turn=turn+1,player_health=player_health-md,monster_health=monster_health-damage WHERE id=e.id RETURNING * INTO e; IF e.monster_health<=0 THEN UPDATE public.fc_combat_encounters SET status='won',result='胜利' WHERE id=e.id; ELSIF e.player_health<=0 THEN UPDATE public.fc_combat_encounters SET status='lost',result='战败' WHERE id=e.id; END IF; RETURN public.fc_get_combat(); END $$;
REVOKE ALL ON FUNCTION public.fc_get_combat(),public.fc_use_lure(),public.fc_spawn_combat(),public.fc_resolve_combat(text) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.fc_get_combat(),public.fc_use_lure(),public.fc_spawn_combat(),public.fc_resolve_combat(text) TO authenticated;
