ALTER TABLE public.fc_characters ADD COLUMN lure_received boolean NOT NULL DEFAULT false,ADD COLUMN lure_room uuid,ADD COLUMN encounter_checked_at timestamptz NOT NULL DEFAULT now();
UPDATE public.fc_monster_definitions SET region_depth=CASE WHEN realm_index<=1 THEN 'outer' ELSE 'inner' END;
CREATE FUNCTION public.fc_claim_lure_supply() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; free integer;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid() FOR UPDATE; IF c.id IS NULL OR c.lure_received THEN RETURN; END IF;
SELECT n INTO free FROM generate_series(1,200) n WHERE NOT EXISTS(SELECT 1 FROM public.fc_inventory_slots WHERE character_id=c.id AND slot=n) ORDER BY n LIMIT 1;
IF free IS NULL THEN RETURN; END IF;
INSERT INTO public.fc_inventory_slots(character_id,slot,item_key,item_name,quantity,category,description) VALUES(c.id,free,'lure_powder','引妖散',10,'消耗品','全境界可用。野外或官道使用，当前区域遇怪概率100%，离开区域失效。');
UPDATE public.fc_characters SET lure_received=true WHERE id=c.id; END $$;
REVOKE ALL ON FUNCTION public.fc_claim_lure_supply() FROM PUBLIC;GRANT EXECUTE ON FUNCTION public.fc_claim_lure_supply() TO authenticated;
CREATE OR REPLACE FUNCTION public.fc_use_lure() RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; p public.fc_character_positions; cell public.fc_world_cells; r public.fc_world_rooms; item public.fc_inventory_slots;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid() FOR UPDATE; SELECT * INTO p FROM public.fc_character_positions WHERE character_id=c.id; SELECT * INTO cell FROM public.fc_world_cells WHERE id=p.cell_id; SELECT * INTO r FROM public.fc_world_rooms WHERE id=cell.room_id; IF r.is_safe_city OR r.kind NOT IN ('wilderness','forest','road') THEN RAISE EXCEPTION '只能在野外或官道使用引妖散'; END IF; SELECT * INTO item FROM public.fc_inventory_slots WHERE character_id=c.id AND item_key='lure_powder' ORDER BY slot LIMIT 1 FOR UPDATE; IF item.slot IS NULL THEN RAISE EXCEPTION '没有引妖散'; END IF; IF item.quantity=1 THEN DELETE FROM public.fc_inventory_slots WHERE character_id=c.id AND slot=item.slot; ELSE UPDATE public.fc_inventory_slots SET quantity=quantity-1 WHERE character_id=c.id AND slot=item.slot; END IF; UPDATE public.fc_characters SET lure_room=r.id WHERE id=c.id; RETURN jsonb_build_object('message','引妖散生效：当前区域遇怪概率提升至100%，下一次判定必定遇怪。'); END $$;
CREATE OR REPLACE FUNCTION public.fc_spawn_combat() RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; p public.fc_character_positions; cell public.fc_world_cells; r public.fc_world_rooms; m public.fc_monster_definitions; e public.fc_combat_encounters; chance numeric; allowed integer;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid() FOR UPDATE; SELECT * INTO p FROM public.fc_character_positions WHERE character_id=c.id; SELECT * INTO cell FROM public.fc_world_cells WHERE id=p.cell_id; SELECT * INTO r FROM public.fc_world_rooms WHERE id=cell.room_id; IF r.is_safe_city OR r.kind NOT IN ('wilderness','forest','road') THEN RETURN public.fc_get_combat(); END IF; SELECT * INTO e FROM public.fc_combat_encounters WHERE character_id=c.id AND status='active' LIMIT 1; IF e.id IS NOT NULL THEN RETURN public.fc_get_combat(); END IF; IF EXISTS(SELECT 1 FROM public.fc_city_journeys WHERE character_id=c.id) THEN RETURN jsonb_build_object('active',false); END IF; IF now()-c.encounter_checked_at<interval '5 seconds' THEN RETURN jsonb_build_object('active',false); END IF; UPDATE public.fc_characters SET encounter_checked_at=now() WHERE id=c.id; IF random()>(CASE WHEN c.lure_room=r.id THEN 1 ELSE r.encounter_rate END) THEN RETURN jsonb_build_object('active',false); END IF; allowed:=CASE WHEN r.region_depth='outer' THEN least(1,c.realm_index+1) WHEN r.region_depth='inner' THEN least(2,c.realm_index+1) ELSE 2 END; SELECT * INTO m FROM public.fc_monster_definitions WHERE region_depth=CASE WHEN r.region_depth='inner' THEN 'inner' ELSE 'outer' END AND r.region_depth<>'core' AND realm_index<=least(2,c.realm_index+1) ORDER BY random() LIMIT 1; IF m.id IS NULL THEN RETURN jsonb_build_object('active',false); END IF; INSERT INTO public.fc_combat_encounters(character_id,room_id,monster_id,monster_count,player_health,monster_health) VALUES(c.id,r.id,m.id,1+floor(random()*3)::int,(public.fc_get_attributes()->>'health')::numeric,m.base_health) RETURNING * INTO e; RETURN public.fc_get_combat(); END $$;
CREATE OR REPLACE FUNCTION public.fc_get_combat() RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE c public.fc_characters; e public.fc_combat_encounters; m public.fc_monster_definitions;
BEGIN SELECT * INTO c FROM public.fc_characters WHERE owner_id=public.fc_require_uid(); SELECT * INTO e FROM public.fc_combat_encounters WHERE character_id=c.id ORDER BY created_at DESC LIMIT 1; IF e.id IS NULL THEN RETURN jsonb_build_object('active',false); END IF; SELECT * INTO m FROM public.fc_monster_definitions WHERE id=e.monster_id; RETURN jsonb_build_object('active',e.status='active','encounter',to_jsonb(e),'monster',to_jsonb(m),'player_realm',c.realm,'player_name',c.display_name,'player_avatar_key',c.avatar_key); END $$;
INSERT INTO public.fc_world_rooms(id,state_name,city_name,name,kind,danger,encounter_rate,description,city_id,template_id,region_depth)
SELECT md5(r.id::text||':depth:'||d.depth)::uuid,r.state_name,r.city_name,replace(r.name,'外围',d.label),'forest',d.danger,d.rate,'深入山野的'||d.label||'。'||d.note,r.city_id,NULL,d.depth FROM public.fc_world_rooms r CROSS JOIN (VALUES ('inner','内围',0.8,0.4,'金丹至元婴可进入。'),('core','核心',1.0,0.5,'出窍至化神可进入，高阶怪物开发中。')) d(depth,label,danger,rate,note) WHERE r.kind='forest' AND r.region_depth='outer';
INSERT INTO public.fc_world_cells(id,room_id,x,y,terrain) SELECT md5(r.id::text||':'||x||':'||y)::uuid,r.id,x,y,'forest' FROM public.fc_world_rooms r CROSS JOIN generate_series(-1,1) x CROSS JOIN generate_series(-1,1) y WHERE region_depth IN ('inner','core');
INSERT INTO public.fc_world_exits SELECT a.id,'south',b.id FROM public.fc_world_rooms r JOIN public.fc_world_cells a ON a.room_id=r.id AND a.x=0 AND a.y=1 JOIN public.fc_world_rooms dest ON dest.id=md5(r.id::text||':depth:inner')::uuid JOIN public.fc_world_cells b ON b.room_id=dest.id AND b.x=0 AND b.y=-1 WHERE r.region_depth='outer' AND r.kind='forest';
INSERT INTO public.fc_world_exits SELECT b.id,'north',a.id FROM public.fc_world_rooms r JOIN public.fc_world_cells a ON a.room_id=r.id AND a.x=0 AND a.y=1 JOIN public.fc_world_rooms dest ON dest.id=md5(r.id::text||':depth:inner')::uuid JOIN public.fc_world_cells b ON b.room_id=dest.id AND b.x=0 AND b.y=-1 WHERE r.region_depth='outer' AND r.kind='forest';
INSERT INTO public.fc_world_exits SELECT a.id,'south',b.id FROM public.fc_world_rooms r JOIN public.fc_world_cells a ON a.room_id=md5(r.id::text||':depth:inner')::uuid AND a.x=0 AND a.y=1 JOIN public.fc_world_cells b ON b.room_id=md5(r.id::text||':depth:core')::uuid AND b.x=0 AND b.y=-1 WHERE r.region_depth='outer' AND r.kind='forest';
INSERT INTO public.fc_world_exits SELECT b.id,'north',a.id FROM public.fc_world_rooms r JOIN public.fc_world_cells a ON a.room_id=md5(r.id::text||':depth:inner')::uuid AND a.x=0 AND a.y=1 JOIN public.fc_world_cells b ON b.room_id=md5(r.id::text||':depth:core')::uuid AND b.x=0 AND b.y=-1 WHERE r.region_depth='outer' AND r.kind='forest';
UPDATE public.fc_world_rooms SET name=CASE WHEN city_id=1 THEN '黑森林外围' ELSE city_name||'·'||(ARRAY['苍松林','赤枫谷','雾竹岭','乱石山','碧水泽'])[(city_id%5)+1]||'外围' END WHERE region_depth='outer' AND kind='forest';
UPDATE public.fc_world_rooms r SET name=replace(o.name,'外围',CASE r.region_depth WHEN 'inner' THEN '内围' ELSE '核心' END) FROM public.fc_world_rooms o WHERE r.id=md5(o.id::text||':depth:'||r.region_depth)::uuid;
CREATE OR REPLACE FUNCTION public.fc_move_world(p_direction text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_uid text:=public.fc_require_uid(); v_me public.fc_characters; v_pos public.fc_character_positions; v_cell public.fc_world_cells; v_next public.fc_world_cells; dx integer:=0; dy integer:=0;
BEGIN
 SELECT * INTO v_me FROM public.fc_characters WHERE owner_id=v_uid; IF v_me.id IS NULL THEN RAISE EXCEPTION '请先入世'; END IF;
 PERFORM public.fc_get_world_state(); SELECT * INTO v_pos FROM public.fc_character_positions WHERE character_id=v_me.id FOR UPDATE; IF v_pos.cell_id IS NULL THEN PERFORM public.fc_get_world_state(); SELECT * INTO v_pos FROM public.fc_character_positions WHERE character_id=v_me.id; END IF;
 IF EXISTS(SELECT 1 FROM public.fc_city_journeys WHERE character_id=v_me.id) THEN RAISE EXCEPTION '正在城际旅行，抵达前不能移动'; END IF;
 SELECT * INTO v_cell FROM public.fc_world_cells WHERE id=v_pos.cell_id;
 IF p_direction='north' THEN dy:=-1; ELSIF p_direction='south' THEN dy:=1; ELSIF p_direction='west' THEN dx:=-1; ELSIF p_direction='east' THEN dx:=1; ELSE RAISE EXCEPTION '方向无效'; END IF;
 SELECT n.* INTO v_next FROM public.fc_world_cells n WHERE n.id=CASE WHEN v_cell.room_id='10000000-0000-0000-0000-000000000005' AND v_cell.x=0 AND v_cell.y=-1 AND p_direction='north' THEN (SELECT c.id FROM public.fc_world_cells c JOIN public.fc_world_rooms r ON r.id=c.room_id WHERE r.family_id=v_me.family_id AND r.template_id='10000000-0000-0000-0000-000000000001' AND c.x=0 AND c.y=1) ELSE public.fc_world_next_cell(v_cell.id,p_direction) END;
 IF v_next.id IS NULL THEN RAISE EXCEPTION '这里没有可通行的道路'; END IF;
 IF EXISTS(SELECT 1 FROM public.fc_combat_encounters WHERE character_id=v_me.id AND status='active') THEN RAISE EXCEPTION '战斗中不能移动'; END IF; IF EXISTS(SELECT 1 FROM public.fc_world_rooms WHERE id=v_next.room_id AND (region_depth='inner' AND v_me.realm_index<2 OR region_depth='core' AND v_me.realm_index<4)) THEN RAISE EXCEPTION '内围需金丹及以上，核心需出窍及以上'; END IF; PERFORM public.fc_claim_cultivation();
 UPDATE public.fc_character_positions SET cell_id=v_next.id,updated_at=now() WHERE character_id=v_me.id;
 UPDATE public.fc_characters SET lure_room=NULL WHERE id=v_me.id AND lure_room IS DISTINCT FROM v_next.room_id;
 RETURN public.fc_get_world_state();
END $$;
GRANT EXECUTE ON FUNCTION public.fc_get_world_state(),public.fc_move_world(text) TO authenticated;
