import {useState} from 'react';import {Sprout,Shield,Swords,BookOpen,ChevronRight} from 'lucide-react';
import {auraRequirement,auraRate,type GameState} from './lib/types';
import {AttributePanel} from './AttributePanel';import {BreakthroughPanel} from './BreakthroughPanel';import {ManualsPanel} from './ManualsPanel';
export function CultivationHome({state,setState,setError,power,avatar,stopped,busy,perform,defense}:{state:GameState;setState:(s:GameState)=>void;setError:(s:string)=>void;power:number|null;avatar:string;stopped:boolean;busy:boolean;perform:(name:string,args?:Record<string,unknown>)=>Promise<void>;defense:React.ReactNode}){
 const [tab,setTab]=useState('rest');const c=state.character!;const family=state.families.find(f=>f.id===c.family_id);const aura=Number(c.cultivation)/100*auraRequirement(c);const limit=Number(c.capacity)/100*auraRequirement(c);
 return <div className="cultivation-home"><section className="cultivator-banner"><div className="cultivator-identity"><div className="portrait">{avatar?<img src={avatar} alt="修士头像"/>:c.display_name.slice(0,1)}</div><div><span className="eyebrow">{family?.name}</span><h2>{c.display_name}</h2><p>{c.realm} · {c.realm_grade}品</p></div></div><div className="cultivator-power"><span>战力</span><strong>{power===null?'—':power.toLocaleString('zh-CN')}</strong><small>灵石 {Number(c.spirit_stones||0).toLocaleString('zh-CN')}</small></div></section><div className="cultivator-facts"><span>寿元 <b>{c.lifespan}年</b></span><span>{c.root}灵根</span><span>道基 <b>{c.foundation}</b></span></div><div className="cultivation-tabs">{([['rest','闭关',Sprout],['manuals','妙法',BookOpen],['attributes','属性',Shield],['breakthrough','突破',Swords]] as const).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</div>
 {tab==='rest'?<section className="rest-surface"><div className="section-title"><h3>静室闭关</h3><span className={stopped?'state-badge warning':'state-badge'}>{stopped?'已停止':'灵气流转'}</span></div>{defense}<div className="meditation-scene"><img src="monsters/core_ice_luan.png" alt="霜翼冰鸾与雪岭"/><div><span>吐纳周天</span><strong>{aura.toFixed(1)}<small> / {limit.toFixed(1)} 灵气</small></strong></div></div><div className="progress"><div style={{width:`${Math.min(100,aura/Math.max(1,limit)*100)}%`}}/></div><div className="rest-metrics"><span>突破需求 <b>{auraRequirement(c)}点</b></span><span>修炼速度 <b>{auraRate(c)}点/分</b></span></div><div className="rest-actions"><button className="primary" disabled={busy||stopped} onClick={()=>void perform('fc_claim_cultivation')}><Sprout size={17}/>结算闭关</button><button className="secondary" disabled={busy||Boolean(c.worship_until&&new Date(c.worship_until)>new Date())} onClick={()=>void perform('fc_worship_ancestral_hall')}><Shield size={17}/>祭拜宗祠</button></div><button className="breakthrough-link" onClick={()=>setTab('breakthrough')}>灵气圆满，前往突破<ChevronRight size={16}/></button><p className="muted rest-note">离线最多结算12小时。扩灵丹提高容量，剩余灵气流入下一层。</p></section>:tab==='manuals'?<ManualsPanel setError={setError} onChange={()=>void perform('fc_get_state')}/>:tab==='attributes'?<AttributePanel refreshKey={`${c.realm}:${c.last_claim_at}`} setError={setError}/>:<BreakthroughPanel state={state} setState={setState} setError={setError}/>}
 </div>;
}
