import {useEffect,useRef,useState,type ReactNode} from 'react';import {createPortal} from 'react-dom';import {EyeOff,MessageCircle} from 'lucide-react';
export function DraggableChat({children,onOpen}:{children:ReactNode;onOpen:()=>void}){
 const [hidden,setHidden]=useState(false),[position,setPosition]=useState<{x:number;y:number}|null>(null),[anchor,setAnchor]=useState<HTMLElement|null>(null);
 const box=useRef<HTMLDivElement>(null),gesture=useRef<{x:number;y:number;ox:number;oy:number;active:boolean;moved:boolean}|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),suppress=useRef(false);
 useEffect(()=>{const find=()=>{const el=document.getElementById('meditation-chat-anchor');setAnchor(el&&el.getBoundingClientRect().width>0?el:null)};find();const observer=new MutationObserver(find);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',find);return()=>{observer.disconnect();window.removeEventListener('resize',find);if(timer.current)clearTimeout(timer.current)}},[]);
 const finish=()=>{if(timer.current)clearTimeout(timer.current);if(gesture.current?.moved)suppress.current=true;gesture.current=null};
 const content=hidden?<button className="restore-chat" onClick={()=>setHidden(false)}><MessageCircle size={14}/>显示聊天</button>:<div ref={box} className={position||!anchor?'drag-chat detached':'drag-chat embedded'} style={position?{left:position.x,top:position.y}:undefined} onPointerDown={e=>{if((e.target as Element).closest('button'))return;const r=box.current!.getBoundingClientRect();gesture.current={x:e.clientX,y:e.clientY,ox:r.left,oy:r.top,active:false,moved:false};suppress.current=false;timer.current=setTimeout(()=>{if(gesture.current)gesture.current.active=true},400);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const g=gesture.current;if(!g)return;if(!g.active){if(Math.abs(e.clientX-g.x)+Math.abs(e.clientY-g.y)>10)finish();return}g.moved=true;setPosition({x:Math.max(0,Math.min(innerWidth-(box.current?.offsetWidth||160),g.ox+e.clientX-g.x)),y:Math.max(0,Math.min(innerHeight-(box.current?.offsetHeight||80),g.oy+e.clientY-g.y))})}} onPointerUp={finish} onPointerCancel={finish} onClick={()=>{if(suppress.current){suppress.current=false;return}onOpen()}}><button className="hide-chat" aria-label="隐藏聊天浮窗" onClick={e=>{e.stopPropagation();setHidden(true)}}><EyeOff size={12}/></button>{children}{position&&<button className="reset-chat" onClick={e=>{e.stopPropagation();setPosition(null)}}>归位</button>}</div>;
 return anchor?createPortal(content,anchor):content;
}
