import {Tutorial} from './Tutorial';
import {useState} from 'react';
import {BookOpen,UserRound,Skull} from 'lucide-react';
import {auth,rpc,errorText} from './lib/backend';
import type {GameState} from './lib/types';
export function MorePage({state,setState,setError,power,onRetired,children}:{state:GameState;setState:(s:GameState|null)=>void;setError:(s:string)=>void;power:number|null;onRetired:()=>void;children:React.ReactNode}){const [tab,setTab]=useState<'profile'|'guide'>('profile');const [profileSection,setProfileSection]=useState<'edit'|'retire'>('edit');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const c=state.character!;const retire=async()=>{setBusy(true);try{await rpc('fc_retire',{p_confirmation:confirm});await auth?.signOut();setState(null);onRetired()}catch(e){setError(errorText(e))}finally{setBusy(false)}};return <section className="more-page"><div className="more-tabs"><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}><UserRound size={17}/>个人主页</button><button className={tab==='guide'?'active':''} onClick={()=>setTab('guide')}><BookOpen size={17}/>新手教程</button></div>{tab==='profile'?<><div className="profile-hero"><div className="portrait">{c.display_name.slice(0,1)}</div><div><h2>{c.display_name}</h2><p>{c.realm} · {c.title}</p><strong>战力 {power===null?'—':power.toLocaleString('zh-CN')}</strong></div></div><div className="ranking-tabs"><button onClick={()=>setProfileSection('edit')}>编辑资料</button><button onClick={()=>setProfileSection('retire')}>坐化注销</button></div>{profileSection==='edit'?children:<section className="retire-zone"><h3><Skull size={18}/>坐化</h3><p>坐化等同永久注销当前修士。修为、物品、灵石不可恢复；身世保留在族谱。立族修士坐化后，立族名额重新开放。</p><input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="输入：确认坐化"/><button className="secondary danger" disabled={busy||confirm!=='确认坐化'} onClick={()=>void retire()}>{busy?'坐化中……':'确认坐化并释放名额'}</button></section>}</>:<Tutorial/>}</section>}
function Guide(){return <div className="guide"><h2>入世手册</h2>{[['入世','前50名拥有立族资格；之后作为真人道侣的子女出生。'],['修炼','城内可安全闭关；野外需要金刚阵。灵气达到本层需求才能突破。'],['家族','家族共享宗祠、后山灵脉、灵矿和灵田。族长可编辑家族招募条件。'],['制作','家族页进入炼器、炼丹、画符或功法创作，先采材料再制作。'],['大世界','点击大世界进入九宫格房间，点格子或地点开始自动寻路。'],['战斗','荒原和森林按概率遭遇妖兽，战斗弹窗会自动回合结算。'],['功法','卷二学习无名心法与无名战技，心法和战技会改变修炼与战斗。']].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div>}



