import {EquipmentPanel} from './EquipmentPanel';
import {useEffect,useState} from 'react';
import {Package,X} from 'lucide-react';
import {rpc,errorText} from './lib/backend';
export interface InventoryState{capacity:number;used:number;items:Array<{slot:number;item_key:string;item_name:string;quantity:number;category:string;description:string}>}
export function StoragePage({setError}:{setError:(value:string)=>void}){const [inventory,setInventory]=useState<InventoryState|null>(null);const [version,setVersion]=useState(0);const [tab,setTab]=useState('bag');useEffect(()=>{let live=true;rpc<InventoryState>('fc_get_inventory').then(v=>{if(live)setInventory(v)}).catch(e=>{if(live)setError(errorText(e))});return()=>{live=false}},[setError,version]);return inventory?<><div className="ranking-tabs"><button className={tab==='bag'?'active':''} onClick={()=>setTab('bag')}>储物袋</button><button className={tab==='gear'?'active':''} onClick={()=>setTab('gear')}>随身装备</button></div>{tab==='gear'?<EquipmentPanel setError={setError} onChange={()=>setVersion(v=>v+1)}/>:<StorageGrid inventory={inventory} onUse={async key=>{try{if(key==='lure_powder')await rpc('fc_use_lure');else await rpc('fc_consume_item',{p_key:key});setVersion(v=>v+1)}catch(e){setError(errorText(e));throw e}}}/>}</>:<div className="empty">正在打开储物空间……</div>}
export function StorageGrid({inventory,onUse}:{inventory:InventoryState;onUse?:(key:string)=>Promise<void>}){const [bagPage,setBagPage]=useState(0);const [using,setUsing]=useState(false);const [selected,setSelected]=useState<InventoryState['items'][number]|null>(null);const items=new Map(inventory.items.map(i=>[i.slot,i]));return <section className="storage-page"><div className="section-title"><h2><Package size={24}/>储物</h2><span>已用 {inventory.used} / {inventory.capacity} 格</span></div><p className="muted">材料、丹药、器物和其他物品都存放在这里。点击物品查看详情。</p><div className="storage-grid">{Array.from({length:Math.min(25,inventory.capacity-bagPage*25)},(_,i)=>{const slot=bagPage*25+i+1,item=items.get(slot);return <button key={slot} aria-label={item?`${item.item_name}，数量 ${item.quantity}`:`空格 ${slot}`} className={item?'storage-slot occupied':'storage-slot'} disabled={!item} onClick={()=>item&&setSelected(item)}><small>{slot}</small>{item&&<><strong>{item.item_name}</strong><span>×{item.quantity}</span></>}</button>})}</div><div className="page-controls"><button disabled={bagPage===0} onClick={()=>setBagPage(p=>p-1)}>上一页</button><span>{bagPage+1} / {Math.ceil(inventory.capacity/25)}</span><button disabled={(bagPage+1)*25>=inventory.capacity} onClick={()=>setBagPage(p=>p+1)}>下一页</button></div>{selected&&<div className="drawer-backdrop storage-backdrop"><section className="storage-detail"><div className="section-title"><h3>{selected.item_name}</h3><button aria-label="关闭物品详情" onClick={()=>setSelected(null)}><X/></button></div><p>{selected.category} · 数量 {selected.quantity}</p><p>{selected.description||'暂无物品描述。'}</p>{onUse&&(['丹药','符箓','功法'].includes(selected.category)||selected.item_key==='lure_powder')&&<button className="primary" disabled={using} onClick={async()=>{setUsing(true);try{await onUse(selected.item_key);setSelected(null)}catch{ /* Keep the item open after a rejected use. */ }finally{setUsing(false)}}}>{selected.category==='功法'?'学习':'使用'}</button>}</section></div>}</section>}



