import {useEffect,useState} from 'react';
import {rpc,errorText} from './lib/backend';
interface Recipe{id:string;name:string;profession:string;realm_min:number;spirit_cost:number;ingredients:Record<string,number>;description:string;success_rate:number}
interface WorkshopState{realm_index:number;consciousness:number;craft_bonus:number;skills:Record<string,number>;recipes:Recipe[];inventory:{items:Array<{item_key:string;item_name:string;quantity:number}>}}
const modes=[['smith','炼器'],['alchemy','炼丹'],['talisman','画符'],['author','创作功法']] as const;
export function Workshop({setError}:{setError:(s:string)=>void}){
 const [data,setData]=useState<WorkshopState|null>(null),[mode,setMode]=useState<string>('smith'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[recipePage,setRecipePage]=useState(0);
 useEffect(()=>{void rpc<WorkshopState>('fc_get_workshop').then(setData).catch(e=>setError(errorText(e)))},[setError]);
 const act=async(name:string,args:Record<string,unknown>)=>{setBusy(true);try{const r=await rpc<WorkshopState&{workshop?:WorkshopState;message?:string}>(name,args);setData(r.workshop||r);setMessage(r.message||'采集成功，材料已放入储物。')}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 if(!data)return <p>正在读取家族工坊……</p>;
 const material=(key:string)=>data.inventory.items.find(i=>i.item_key===key)?.item_name||({ore:'灵矿石',hide:'妖兽皮',blood:'妖兽血',herb:'药草',fiber:'纸材纤维'}[key.split('_')[0]]?`${['练气','筑基','金丹','元婴','出窍','化神'][Number(key.split('_')[1])]}${({ore:'灵矿石',hide:'妖兽皮',blood:'妖兽血',herb:'药草',fiber:'纸材纤维'} as Record<string,string>)[key.split('_')[0]]}`:key==='talisman_paper'?'符纸':key);
 return <section className="paper-section"><h3>家族工坊</h3><div className="ranking-tabs">{modes.map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>{setMode(id);setRecipePage(0)}}>{label}</button>)}</div><p className="muted">神识 {Number(data.consciousness).toFixed(1)} · {modes.find(m=>m[0]===mode)?.[1]}水平 {data.skills[mode]} · 心境成功率加成 {data.craft_bonus}个百分点</p><div className="action-row"><button className="secondary" disabled={busy} onClick={()=>void act('fc_gather',{p_kind:'ore'})}>灵矿挖矿</button><button className="secondary" disabled={busy} onClick={()=>void act('fc_gather',{p_kind:'herb'})}>灵田采药</button><button className="secondary" disabled={busy} onClick={()=>void act('fc_gather',{p_kind:'fiber'})}>灵田采纸材</button></div><p className="muted">采集需先走到本族灵矿或灵田，每次3份，冷却30秒。制作需到对应家族设施；失败消耗本次材料及神识。</p>{message&&<p role="status">{message}</p>}{mode==='author'&&<div className="action-row"><button className="secondary" disabled={busy} onClick={()=>void act('fc_profession_research',{p_skill:'astrology'})}>观星研究 · {data.skills.astrology}级</button><button className="secondary" disabled={busy} onClick={()=>void act('fc_profession_research',{p_skill:'medicine'})}>穴位研究 · {data.skills.medicine}级</button></div>}<div className="recipe-list">{data.recipes.filter(r=>r.profession===mode).slice(recipePage*3,recipePage*3+3).map(r=><article key={r.id} className="recipe-row"><h3>{r.name}</h3><p>{r.description}</p><p>{Object.entries(r.ingredients).map(([key,count])=>`${material(key)} ${data.inventory.items.filter(i=>i.item_key===key).reduce((n,i)=>n+i.quantity,0)}/${count}`).join(' · ')}</p><small>需要{['练气','筑基','金丹','元婴','出窍','化神'][r.realm_min]} · 神识{r.spirit_cost} · 成功率{Math.min(95,r.success_rate+data.craft_bonus+Math.min(5,(data.skills[mode]||1)-1))}%</small><button className="primary" disabled={busy||data.realm_index<r.realm_min||data.consciousness<r.spirit_cost} onClick={()=>void act('fc_craft',{p_recipe:r.id})}>制作</button></article>)}</div><div className="page-controls"><button disabled={recipePage===0} onClick={()=>setRecipePage(p=>p-1)}>上一页</button><span>{recipePage+1} / {Math.max(1,Math.ceil(data.recipes.filter(r=>r.profession===mode).length/3))}</span><button disabled={(recipePage+1)*3>=data.recipes.filter(r=>r.profession===mode).length} onClick={()=>setRecipePage(p=>p+1)}>下一页</button></div></section>;
}



