const STATE_COLORS=['#b34832','#d07a21','#b39625','#7a992a','#368d47','#208c73','#278c98','#347eb6','#4365a0','#665994','#915787','#b95776','#864530','#9b672e','#777f29','#457446','#337267','#3a6e80','#4d6a87','#716d93','#9a6575','#c38368','#83956b','#689593'];
import {useEffect,useRef,useState} from 'react';
import {X,Map as MapIcon,Square,Users} from 'lucide-react';
import {getWorldState,moveWorld,errorText,publicProfile,socialAction,rpc} from './lib/backend';
import type {WorldState} from './lib/types';
type Direction='north'|'south'|'east'|'west';
export function findRoute(world:WorldState,target:string):Direction[]|null{
 const edges=world.navigation?.edges||[];const queue=[world.cell.id];const previous=new Map<string,{from:string;direction:Direction}>();const seen=new Set(queue);
 for(let i=0;i<queue.length;i++){const id=queue[i];if(id===target){const route:Direction[]=[];let at=id;while(at!==world.cell.id){const p=previous.get(at)!;route.unshift(p.direction);at=p.from}return route}for(const e of edges){if(e.from===id&&!seen.has(e.to)){seen.add(e.to);previous.set(e.to,{from:id,direction:e.direction});queue.push(e.to)}}}return null;
}
export function WorldExplorer({setError}:{setError:(v:string)=>void}){
 const [world,setWorld]=useState<WorldState|null>(null),[walking,setWalking]=useState(false),[log,setLog]=useState(''),[expanded,setExpanded]=useState(false),[mapLevel,setMapLevel]=useState<'city'|'state'|'continent'>('city'),[nearby,setNearby]=useState(false),[profile,setProfile]=useState<Record<string,unknown>|null>(null),[person,setPerson]=useState<{id:string;name:string}|null>(null);
 const state=useRef(world);const run=useRef(0);const locked=useRef(false);state.current=world;
 useEffect(()=>{const halt=()=>{if(locked.current){run.current++;setLog('遭遇妖兽，自动寻路已停止。')}};window.addEventListener('combat-start',halt);return()=>window.removeEventListener('combat-start',halt)},[]);
 useEffect(()=>{let live=true;const refresh=async()=>{if(locked.current)return;try{const w=await getWorldState();if(live)setWorld(w)}catch(e){if(live)setError(errorText(e))}};void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},30000);return()=>{live=false;run.current++;clearInterval(timer)}},[setError]);
 const stop=()=>{run.current++;setLog('已取消自动寻路，停在当前格子。')};
 const cancel=async()=>{stop();if(world?.journey){try{const next=await rpc<WorldState>('fc_cancel_city_journey');state.current=next;setWorld(next);setLog('已取消官道旅行，返回出发地点。')}catch(e){setError(errorText(e))}}};
 const travel=async(target:string,label:string)=>{if(locked.current)return;const w=state.current;if(w?.journey){setError('正在城际旅行，抵达前才能在城内移动。');return}if(!w)return;const path=findRoute(w,target);if(path===null){setError('这个地点暂无可通行路线。');return}if(!path.length){setLog('你已经在这里。');return}const token=++run.current;locked.current=true;setWalking(true);setExpanded(false);setLog(`正在前往${label}，共 ${path.length} 步……`);try{for(let i=0;i<path.length&&token===run.current;i++){const next=await moveWorld(path[i]);if(token!==run.current){setWorld(next);break}state.current=next;setWorld(next);if(next.encounter){run.current++;setLog('遭遇妖兽，自动寻路已停止。');break}const exit=next.exits?.find(e=>e.from_cell===next.cell.id);if(exit&&i===path.length-1){try{const afterExit=await moveWorld(exit.direction as Direction);state.current=afterExit;setWorld(afterExit);setLog(`已通过出口，进入${afterExit.room.name}。`)}catch(e){setError(errorText(e))}break}setLog(`前往${label}：${i+1}/${path.length} 步 · ${next.room.name}`);if(i<path.length-1)await new Promise(resolve=>setTimeout(resolve,350))}if(token===run.current)setLog(`已到达${label}。`)}catch(e){run.current++;setError(errorText(e));setLog('道路受阻，寻路已停止。')}finally{locked.current=false;setWalking(false)}};
 const journey=async(id:number)=>{if(id===world?.room.city_id){setLog('你已经在这座城池。');return}if(!world?.atlas?.roads.some(e=>e.a===world.room.city_id&&e.b===id||e.b===world.room.city_id&&e.a===id)){setError('必须按城市连接的方式走，请先前往相邻城池。');return}if(walking||world?.journey)return;try{const next=await rpc<WorldState>('fc_start_city_journey',{p_destination:id,p_mode:'walk'});setWorld(next);state.current=next;setExpanded(false);setLog('已沿官道出发，30秒后抵达相邻城池。')}catch(e){setError(errorText(e))}};
 const goRoom=(id:string,name:string)=>{const cells=world?.navigation?.cells.filter(c=>c.room_id===id)||[];const target=cells.find(c=>c.x===0&&c.y===0)||cells[0];if(target)void travel(target.id,name)};
 const inspect=async(p:{id:string;name:string})=>{setPerson(p);setProfile(null);try{setProfile(await publicProfile(p.id) as Record<string,unknown>)}catch(e){setError(errorText(e))}};
 if(!world)return <div className="empty">正在读取城池道路……</div>;
 const rooms=world.map_rooms||[];const routeDistance=(roomId:string)=>{const cells=world.navigation?.cells||[];const target=cells.find(c=>c.room_id===roomId);if(!target)return 999999;const q=[world.cell.id];const dist=new Map([[world.cell.id,0]]);for(const id of q){for(const edge of world.navigation?.edges||[]){if(edge.from!==id||dist.has(edge.to))continue;dist.set(edge.to,(dist.get(id)||0)+1);q.push(edge.to)}}return dist.get(target.id)||999999};const exits=world.exits||[];const position=['西北','北侧','东北','西侧','中央','东侧','西南','南侧','东南'][(world.cell.y+1)*3+world.cell.x+1];
 return <><div className="explorer">
 {(walking||world.journey)&&<div className="active-route-float" role="status"><span>{world.journey?'正在沿官道前往'+(world.atlas?.cities.find(c=>Number(c.id)===Number(world.journey?.destination))?.name||'相邻城池'):walking?'正在自动寻路中':''}</span><button onClick={()=>void cancel()}>取消寻路</button></div>}
 {world.journey&&<RoadJourney world={world} onCancel={()=>void cancel()} onArrive={async()=>{try{const next=await getWorldState();state.current=next;setWorld(next)}catch(e){setError(errorText(e))}}}/>}
 {world.encounter&&<section className="wild-warning" role="alert"><strong>遭遇妖兽：{world.encounter.monster_name||world.encounter.monster?.name||'未知妖兽'}</strong><p>{['练气','筑基','金丹','元婴','出窍','化神'][world.encounter.monster_realm_index]}{world.encounter.monster_layer}层 · {world.encounter.monster_count}只。自动寻路已停止。</p><small>正式战斗结算尚未开放，当前可移动离开这片区域。</small></section>}
 {nearby&&<section className="nearby-top"><h3>附近在线修士</h3>{world.nearby.length?world.nearby.map(p=><button className="secondary" key={p.id} onClick={()=>void inspect(p)}>{p.name} · {p.title}</button>):<p>当前格子暂无其他在线修士。</p>}</section>}
 <div className="explorer-layout"><div className="room-status-line"><h3>{world.room.name}</h3><button className="world-map-float" onClick={()=>setExpanded(true)}>大世界地图</button><span>遇怪 {Math.round(world.room.encounter_rate*100)}%</span><span>危险 {Math.round(world.room.danger*100)}%</span><button onClick={()=>setNearby(v=>!v)}>附近的人 ({world.nearby.length})</button></div><section className="explorer-room"><p className="muted">{world.room.description}</p><div className="click-room-grid">{[-1,0,1].flatMap(y=>[-1,0,1].map(x=>{const cell=world.cells?.find(c=>c.x===x&&c.y===y);const current=x===world.cell.x&&y===world.cell.y;const label=['西北','北侧','东北','西侧','中央','东侧','西南','南侧','东南'][(y+1)*3+x+1];return <button key={`${x}:${y}`} disabled={!cell||walking||current} className={current?'here':''} onClick={()=>cell&&void travel(cell.id,`${world.room.name} ${label}`)}><strong>{current?'● 你':label}</strong><small>{cell?'点击走到这里':'不可通行'}</small>{exits.filter(e=>e.x===x&&e.y===y).map(e=><span key={e.direction}>出口：{e.to_room}</span>)}</button>}))}</div><p className="muted">点击格子移动；点击出口目的地即可走出房间。荒原或森林每次移动判定遇怪，原地等待不触发；当前遇怪概率 {Math.round(world.room.encounter_rate*100)}%。</p><div className="destination-exits">{exits.map(e=>{const room=rooms.find(r=>r.name===e.to_room);return <button className="secondary" disabled={walking} key={e.from_cell+e.direction} onClick={()=>room&&goRoom(room.id,room.name)}>前往 {e.to_room}</button>})}</div></section>
 <aside className="explorer-navigation"><h3>快速寻路</h3><div className="destination-list"><span className="route-group">城内地点 · 按路线距离</span>{[...rooms].sort((a,b)=>{const ac=a.kind==='city'||a.name.includes('城');const bc=b.kind==='city'||b.name.includes('城');if(ac!==bc)return Number(ac)-Number(bc);return routeDistance(a.id)-routeDistance(b.id)}).map(r=><button key={r.id} disabled={walking||r.id===world.room.id} onClick={()=>goRoom(r.id,r.name)}><Square size={12}/>{r.name}<small>{r.id===world.room.id?'当前':routeDistance(r.id)===999999?'不可达':`${routeDistance(r.id)}步`}</small></button>)}<span className="route-group">相邻城池 · 官道</span>{world.atlas?.roads.filter(e=>Number(e.a)===Number(world.room.city_id)||Number(e.b)===Number(world.room.city_id)).map(e=>{const id=Number(e.a)===Number(world.room.city_id)?Number(e.b):Number(e.a);const city=world.atlas?.cities.find(c=>Number(c.id)===id);return <button key={'city-'+id} disabled={walking||Boolean(world.journey)} onClick={()=>void journey(id)}><Square size={12}/>{city?.name}<small>30秒</small></button>})}</div></aside></div>
 {expanded&&<div className="drawer-backdrop city-map-backdrop"><section className="city-map-dialog"><div className="section-title"><h3>{world.room.city_name} · 全城道路</h3><button onClick={()=>setExpanded(false)} aria-label="关闭城池地图"><X/></button></div><p className="muted">拖动地图查看道路，使用 − / ＋ 调整大小。朱砂边框标记当前位置。</p><div className="atlas-tabs">{(['city','state','continent'] as const).map(l=><button key={l} className={mapLevel===l?'active':''} onClick={()=>setMapLevel(l)}>{({city:'城内建筑',state:'本州城池',continent:'环形大陆'})[l]}</button>)}</div>{mapLevel!=='city'&&<div className="state-color-legend">{world.atlas?.states.filter(s=>mapLevel==='continent'||s.name===world.room.state_name).map(s=><span key={s.id}><i style={{background:STATE_COLORS[(Number(s.id)-1)%24]}}/>{s.name}</span>)}</div>}<PanMap key={mapLevel} initialZoom={400} focus={mapLevel==='city' ? {x:world.cell.x,y:world.cell.y} : {x:Number(world.room.city_id||0),y:Number(world.room.city_id||0)}}>{mapLevel==='city'?<CityGraph world={world} onChoose={goRoom}/>:<AtlasMap world={world} level={mapLevel} onChoose={id=>void journey(id)}/>}</PanMap></section></div>}
 </div></>;
}

export function PanMap({children,initialZoom=100,focus}:{children:React.ReactNode;initialZoom?:number;focus?:{x:number;y:number}}){
 const [zoom,setZoom]=useState(initialZoom),[offset,setOffset]=useState({x:0,y:0});useEffect(()=>{setZoom(initialZoom);if(focus){const x=Math.max(-600,Math.min(600,-focus.x*20));const y=Math.max(-450,Math.min(450,-focus.y*20));setOffset({x,y})}else setOffset({x:0,y:0})},[initialZoom,focus?.x,focus?.y]);const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);const moved=useRef(false);
 const change=(step:number)=>setZoom(v=>Math.min(400,Math.max(50,v+step)));
 return <><div className="map-zoom-tools"><button aria-label="缩小地图" onClick={()=>change(-25)}>−</button><output aria-label="地图缩放比例">{zoom}%</output><button aria-label="放大地图" onClick={()=>change(25)}>＋</button><button onClick={()=>{setZoom(100);setOffset({x:0,y:0})}}>回到中心</button></div><div className="city-pan zoom-viewport" onClickCapture={e=>{if(moved.current){e.preventDefault();e.stopPropagation();moved.current=false}}} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};moved.current=false}} onPointerMove={e=>{const d=drag.current;if(!d)return;if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>5){moved.current=true;e.currentTarget.setPointerCapture(e.pointerId);setOffset({x:d.ox+e.clientX-d.x,y:d.oy+e.clientY-d.y})}}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><div className="zoom-map-content" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom/100})`}}>{children}</div></div></>
}
function CityGraph({world,onChoose,compact=false}:{world:WorldState;onChoose:(id:string,name:string)=>void;compact?:boolean}){
 const rooms=world.map_rooms||[];const routeDistance=(roomId:string)=>{const cells=world.navigation?.cells||[];const target=cells.find(c=>c.room_id===roomId);if(!target)return 999999;const q=[world.cell.id];const dist=new Map([[world.cell.id,0]]);for(const id of q){for(const edge of world.navigation?.edges||[]){if(edge.from!==id||dist.has(edge.to))continue;dist.set(edge.to,(dist.get(id)||0)+1);q.push(edge.to)}}return dist.get(target.id)||999999};const position=new Map<string,{x:number;y:number}>();const idNumber=(id:string)=>Number(id.slice(-12));
 for(const r of rooms){const n=idNumber(r.template_id||r.id);let x=550,y=500;if(n===1){x=550;y=390}else if(n===5){x=550;y=560}else if(n===6){x=550;y=740}else if(n===2){x=550;y=900}else if(n===3){x=800;y=900}else if(n===4){x=550;y=1060}else if(n===10){x=550;y=230}else if(n>=11&&n<=18){x=n<15?180:900;y=80+((n-11)%4)*100}else if(n===19){x=550;y=60}else if(n>=20&&n<=22){x=180+(n-20)*370;y=-100}else if(n===30){x=1100;y=560}else if(n===31){x=1100;y=390}else if(n===32){x=1100;y=740}else if(n===33){x=1580;y=560}else if(n>=34&&n<=41){x=n<38?1390:1810;y=230+((n-34)%4)*170}position.set(r.id,{x:x+80,y:y+180})}
 const cells=new Map((world.navigation?.cells||[]).map(c=>[c.id,c.room_id]));const lines=new Set<string>();const pairs:Array<[string,string]>=[];for(const e of world.navigation?.edges||[]){const a=cells.get(e.from),b=cells.get(e.to);if(a&&b&&a!==b){const key=[a,b].sort().join(':');if(!lines.has(key)){lines.add(key);pairs.push([a,b])}}}
 return <svg className={compact?'city-graph compact':'city-graph'} viewBox="0 0 2120 1320" role="img" aria-label="建筑方块和道路连线地图"><g className="city-road-lines">{pairs.map(([a,b])=>{const p=position.get(a),q=position.get(b);return p&&q?<path key={a+b} d={`M ${p.x} ${p.y} H ${(p.x+q.x)/2} V ${q.y} H ${q.x}`}/>:null})}</g>{rooms.map(r=>{const p=position.get(r.id)!;return <g key={r.id} transform={`translate(${p.x-78},${p.y-25})`}><foreignObject width="156" height="54"><button className={r.id===world.room.id?'graph-room current':'graph-room'} onClick={()=>onChoose(r.id,r.name)}>{r.name}</button></foreignObject></g>})}</svg>
}

function AtlasMap({world,level,compact=false,onChoose}:{world:WorldState;level:'state'|'continent';compact?:boolean;onChoose:(id:number)=>void}){
 const atlas=world.atlas;if(!atlas)return <p>正在读取大陆地图</p>;const current=atlas.cities.find(c=>c.id===world.room.city_id);const cities=atlas.cities.filter(c=>level==='continent'||c.state_id===current?.state_id);const bounds=level==='continent'?'0 0 2100 2100':(()=>{const xs=cities.map(c=>Number(c.x)),ys=cities.map(c=>Number(c.y));return `${Math.min(...xs)-150} ${Math.min(...ys)-120} ${Math.max(...xs)-Math.min(...xs)+300} ${Math.max(...ys)-Math.min(...ys)+240}`})();const neighbors=new Set(atlas.roads.filter(e=>e.a===current?.id||e.b===current?.id).map(e=>e.a===current?.id?e.b:e.a));
 return <svg className={compact?'atlas-map compact':'atlas-map'} viewBox={bounds} role="img" aria-label={level==='continent'?'二十四州环形大陆地图':'州域城池连接地图'}>{level==='continent'&&<><rect width="2100" height="2100" fill="#d6e3df"/><circle cx="1000" cy="1000" r="1010" fill="#eee7d8" stroke="#9a743e" strokeWidth="4"/><circle cx="1000" cy="1000" r="340" fill="#c7b29b"/><text x="1000" y="1210" textAnchor="middle" fontSize="30">无人焦土</text><circle cx="1000" cy="1000" r="130" fill="#333c36"/><text x="1000" y="1010" textAnchor="middle" fontSize="34" fill="#fff8eb">黑云山</text><text x="1040" y="2070" textAnchor="middle" fontSize="28">无尽星海 · 开发中</text>{atlas.states.map(s=><text key={s.id} x={Number(s.x)} y={Number(s.y)-90} textAnchor="middle" fill={STATE_COLORS[(Number(s.id)-1)%24]} fontSize="22">{s.name}</text>)}</>}
 {atlas.roads.map(e=>{const a=cities.find(c=>c.id===e.a),b=cities.find(c=>c.id===e.b);return a&&b?<line key={e.a+':'+e.b} x1={Number(a.x)} y1={Number(a.y)} x2={Number(b.x)} y2={Number(b.y)} stroke="#9a743e" strokeWidth="3"/>:null})}
 {cities.map(c=><g key={c.id} transform={`translate(${Number(c.x)},${Number(c.y)})`} role="button" tabIndex={0} aria-label={`${c.name}${c.id===current?.id?' 当前城池':neighbors.has(c.id)?' 可前往':' 非相邻城池'}`} onClick={()=>onChoose(c.id)} onKeyDown={e=>{if(e.key==='Enter')onChoose(c.id)}} style={{cursor:neighbors.has(c.id)?'pointer':'default'}}><title>{atlas.states.find(s=>s.id===c.state_id)?.name} · {c.name}</title><rect x="-32" y="-14" width="64" height="28" rx="2" fill={STATE_COLORS[(Number(c.state_id)-1)%24]} stroke={c.id===current?.id?'#a74635':neighbors.has(c.id)?'#252b29':'#fff8eb'} strokeWidth={c.id===current?.id?5:2}/><text textAnchor="middle" y="5" fontSize="12" fill="#fff8eb">{c.name}</text></g>)}
 </svg>
}

export function RoadJourney({world,onCancel,onArrive}:{world:WorldState;onCancel:()=>void;onArrive:()=>Promise<void>}){
 const [time,setTime]=useState(Date.now());const arrived=useRef(false);const callback=useRef(onArrive);callback.current=onArrive;
 const journey=world.journey!;const end=new Date(journey.arrives_at).getTime();const start=new Date(journey.started_at).getTime();
 useEffect(()=>{arrived.current=false;const update=()=>{const now=Date.now();setTime(now);if(now>=end&&!arrived.current){arrived.current=true;void callback.current().catch(()=>{arrived.current=false})}};update();const timer=setInterval(update,1000);return()=>clearInterval(timer)},[end]);
 const progress=Math.max(0,Math.min(100,(time-start)/Math.max(1,end-start)*100));const seconds=Math.max(0,Math.ceil((end-time)/1000));const target=world.atlas?.cities.find(c=>c.id===journey.destination);const origin=world.atlas?.cities.find(c=>c.id===world.room.city_id);const distance=world.atlas?.roads.find(e=>Math.min(e.a,e.b)===Math.min(Number(world.room.city_id),journey.destination)&&Math.max(e.a,e.b)===Math.max(Number(world.room.city_id),journey.destination))?.distance;
 return <section className="official-road-journey"><div className="section-title"><h3>官道行进 · 徒步</h3><strong>{progress.toFixed(1)}%</strong></div><p>{origin?.name||world.room.city_name} → {target?.name} · 道路距离 {distance||"—"} · 剩余 {Math.floor(seconds/60)}分{seconds%60}秒</p><button className="secondary" onClick={onCancel}>取消自动寻路 · 返回出发点</button></section>
}





